name: shell commands

on:
    - push

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: set Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
      - name: Terraform init
        run: terraform init
      - name: multi line string
        run: |
          pwd
          ls -a
